local:
  service_endpoint    : "http://localhost:8081"
  web_port            : 8888

development:
  web_port            : 8888

test:
  web_port            : 8888

automation:
  service_endpoint    : "http://localhost:8081"
  web_port            : 8889

production:
